#define	STATE_INIT		0
#define	STATE_INIT_W	5
#define	STATE_IDLE		1
#define	STATE_WFCALL	2
#define	STATE_CALLING	3
#define	STATE_WFECALL	4
#define	STATE_WFINCALL	6
#define	STATE_INCALL	7
#define	STATE_WFEINCALL	8
#define	STATE_WFAINCALL	9

#define	NORMAL_CYCLE_MS	30
#define	TIMEOUT_MS		5000
#define	TIMEOUT_C		(TIMEOUT_MS/NORMAL_CYCLE_MS)
